<?php
/**
 * @file
 * Empty shell of a module.
 */

/**
 * Implements hook_form_FORMID_alter().
 */
function islandora_paged_content_pdf_batch_form_islandora_paged_content_upload_pdf_form_alter($form, &$form_state) {
  // Display a warning message to users who could be ingesting a large PDF
  // through the ingest steps.
  if (isset($form_state['islandora']['shared_storage'])) {
    module_load_include('inc', 'islandora', 'includes/ingest.form');
    $shared_storage = islandora_ingest_form_get_shared_storage($form_state);
    drupal_set_message(t('Please note that large PDFs may take a long time to process. Consider using the batch ingester located in the <a href="@url">manage colection</a> interface.', array('@url' => url("islandora/object/{$shared_storage['parent']}/manage/collection"))), 'warning');
  }
}
